### ISSUE TITLE
Error of No such file or directory at the end of model training

### ISSUE THREAD

**Issue by balandongiv** [skjerns/AutoSleepScorerDev#7]
Hi Simon,
at the end of the training, the compiler return the following error trail

>  1.0 min
> can't save plots: [Errno 2] No such file or directory: '.\\plots\\0_edfx-sample_ fc1_ fold_ 0_pure_rnn.png'
> Got an error while saving model: Unable to create file (unable to open file: name = '.\weights\0edfx-samplefc1_0_0.390-0.080', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 302)
> fold 0: val acc/f1: 0.44937/0.12432, test acc/f1: 0.39016/0.08039
> Traceback (most recent call last):
>   File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\pydevd.py", line 1438, in _exec
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "C:/Users/rpb/Documents/OneDrive - Universiti Teknologi PETRONAS/Code Development/sleep staging/run_sample.py", line 58, in <module>
>     plot=True, stop_after=4, balanced=False, cropsize=2800)
>   File "C:\Users\rpb\Documents\OneDrive - Universiti Teknologi PETRONAS\Code Development\sleep staging\keras_utils.py", line 838, in cv
>     tools.save_results(save_dict=save_dict)
>   File "C:\Users\rpb\Documents\OneDrive - Universiti Teknologi PETRONAS\Code Development\sleep staging\tools.py", line 417, in save_results
>     np.set_printoptions(precision=2,threshold=np.nan)
>   File "C:\Users\rpb\anaconda3\envs\sleep staging\lib\site-packages\numpy\core\arrayprint.py", line 259, in set_printoptions
>     floatmode, legacy)
>   File "C:\Users\rpb\anaconda3\envs\sleep staging\lib\site-packages\numpy\core\arrayprint.py", line 95, in _make_options_dict
>     raise ValueError("threshold must be non-NAN, try "
> ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation
> 
> Process finished with exit code 1

To troubleshot, I had comb the [keras_utils.py](https://github.com/skjerns/AutoSleepScorerDev/blob/master/keras_utils.py) and [tools.py](https://github.com/skjerns/AutoSleepScorerDev/blob/master/tools.py) for a line that responsible for creating the directory/ file

` \\plots\\0_edfx-sample_ fc1_ fold_ 0_pure_rnn.png`

and 

` '.\weights\0edfx-samplefc1_0_0.390-0.080'`

However, I am unable to find anywhere the line of code that responsible for this.

Appreciate if you can shed some light.

**Comment by skjerns** [comment]
the folder `plots` and `weights` has to be present before I assume. have you tried to create it manually?

**Comment by balandongiv** [comment]
Thanks for the reply. May I know where this folder should be created? Appreciate for any insights

**Comment by skjerns** [comment]
I think in the folder of the repository

**Comment by balandongiv** [comment]
To confirm, you mean the folders should be created at the main folder where the file README reside?

**Comment by skjerns** [comment]
yes, you could try that?
